spring:
  application:
    name: reportai

  datasource:
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:root}
    url: ${PG_URL:jdbc:postgresql://localhost:5432/reportai}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /reportai.html
  api-docs:
    path: /reportai
  packages-to-scan: com.reportai.controller

ai:
  model: ${AI_MODEL:gemini-2.5-flash}
  prompt:
    system: Você é um especialista em pedagogia e gera relatórios. Quando precisar falar o nome do aluno utilize [NOME_DO_ALUNO]. Escreva tudo em texto corrido em no máximo 7 linhas.
    request: Analise os relatos diários abaixo e gere um relatório descritivo do comportamento do estudante \n %s